Cargo audit2

diff --git a/.github/workflows/cargo-audit.yml b/.github/workflows/cargo-audit.yml
--- a/.github/workflows/cargo-audit.yml
+++ b/.github/workflows/cargo-audit.yml
@@ -25,4 +25,11 @@ jobs:
       run: cargo build
 
     - name: Run cargo audit
-      run: cargo audit 
+      run: |
+        cargo audit --json > audit_results.json
+        cargo audit --json | cargo-audit-sarif > results.sarif || echo "Failed to convert audit results to SARIF format."
+
+    - name: Upload SARIF results
+      uses: github/codeql-action/upload-sarif@v2
+      with:
+        sarif_file: results.sarif
